### ISSUE TITLE
SAML support in docker image

### ISSUE THREAD

**Issue by DanieleVistalli** [phpipam-docker/phpipam-docker#10]
Hi, I'm using your image (and thank you for the quality of the work) but when I try to add a SAML based authentication configuration PHPIPAM's web interface reports:

> php mcrypt extension missing!

In the SAML configuration dialog box.

Would it be possible for you to add the missing library to the build process ?

Thanks in advance.

**Comment by GaryAllan** [comment]
Hi

This has been requested before.

mcrypt was deprecated and removed from php. It's no longer included with Alpine Linux which the docker images are based upon.

The issue is the version of the SAML library in phpIPAM 1.4x still depends on mcrypt.

The v1.5x and nightly images contain an updated SAML library with better compatibility and features and no longer depend on mcrypt.
